/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import funcion.ContenidoCSV;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import funcion.GenerarDatos;
import funcion.GraficaSimulacion;
import funcion.GraficaSimulacionTn;
/**
 *
 * @author yael
 */
public class grafica1 extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    public grafica1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 950, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents
ContenidoCSV contenidoCSV=new ContenidoCSV();private void cargarCsv() {
     ContenidoCSV contenidoCSV = new ContenidoCSV();
        
        // Cargar los datos desde el archivo CSV
        contenidoCSV.cargarDesdeArchivo();

        // Obtener los datos del archivo CSV
        String[] encabezados = contenidoCSV.obtenerEncabezados();
        List<String[]> filas = contenidoCSV.obtenerFilas();

        // Crear el modelo de la tabla con los encabezados
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(encabezados);

        // Agregar las filas al modelo
        for (String[] fila : filas) {
            model.addRow(fila);
        }

        // Asignar el modelo de la tabla al JTable
        JTableCSV.setModel(model);
}

private void calcularValores() {
    DefaultTableModel model = (DefaultTableModel) JTableCSV.getModel();
    int rowCount = model.getRowCount();
    if (rowCount == 0) {
        datoslbl.setText("La tabla está vacía. Carga un archivo CSV primero.");
        return;
    }

    // Asegurarse de que las columnas adicionales para resultados existan
    if (model.getColumnCount() < 6) {
        model.addColumn("Daño Ambiental");
        model.addColumn("Tasa de Natalidad Calculada");
        model.addColumn("Esperanza de Vida Calculada");
    }

    try {
        for (int i = 0; i < rowCount; i++) {
            double tasaNatalidadNormal = Double.parseDouble((String) model.getValueAt(i, 0));
            double esperanzaVidaNormal = Double.parseDouble((String) model.getValueAt(i, 1));
            double relacionDesechos = Double.parseDouble((String) model.getValueAt(i, 2));
            double ocupacionInadecuada = Double.parseDouble((String) model.getValueAt(i, 3));

            // Cálculo de daño ambiental
            double danioAmbiental = relacionDesechos + ocupacionInadecuada;

            // Cálculo de tasa de natalidad
            double tasaNatalidad = tasaNatalidadNormal - (danioAmbiental * 8.35e-5);

            // Cálculo de esperanza de vida
            double esperanzaVida = esperanzaVidaNormal * (1 - danioAmbiental * 0.07);

            // Agregar los resultados calculados directamente en las nuevas columnas
            model.setValueAt(String.format("%.4f", danioAmbiental), i, 4); // Columna "Daño Ambiental"
            model.setValueAt(String.format("%.4f", tasaNatalidad), i, 5); // Columna "Tasa de Natalidad Calculada"
            model.setValueAt(String.format("%.2f", esperanzaVida), i, 6); // Columna "Esperanza de Vida Calculada"
        }

        datoslbl.setText("Valores calculados y añadidos a la tabla.");
    } catch (Exception ex) {
        datoslbl.setText("Error en el cálculo: " + ex.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
