/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import funcion.ContenidoCSV;
import funcion.GenerarDatos;
import funcion.GraficaSimulacion;
import funcion.GraficaSimulacionTn;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author ambro
 */
public class Ingresar_CSV extends javax.swing.JFrame {
private String nombreArchivo="Plantilla/Plantilla.csv";
 private DefaultTableModel originalModel;
    
    public Ingresar_CSV() {
        initComponents();
          
    // Obtener el archivo desde los recursos del proyecto
    File archivoCSV;
    try {
        archivoCSV = new File(getClass().getClassLoader().getResource(nombreArchivo).toURI());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "No se pudo localizar el archivo dentro del proyecto: " + nombreArchivo);
        return;
    }

    // Verificar si el archivo existe
    if (!archivoCSV.exists()) {
        JOptionPane.showMessageDialog(this, "El archivo especificado no existe en los recursos del proyecto: " + nombreArchivo);
        return;
    }

    // Leer el archivo
    try (BufferedReader br = new BufferedReader(new FileReader(archivoCSV))) {
        String line;
        ContenidoCSV contenidoCSV = new ContenidoCSV();
        contenidoCSV.limpiar();

        DefaultTableModel model = (DefaultTableModel) JTableCSV.getModel();
        model.setRowCount(0);
        model.setColumnCount(4); // Fijar el número de columnas a 6

        // Establecer nombres de columna genéricos
        
        while ((line = br.readLine()) != null) {
            // Dividir la línea en columnas
            String[] values = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);

            // Asegurar que haya siempre 6 columnas
            if (values.length < 4) {
                values = Arrays.copyOf(values, 4); // Completar con valores vacíos si faltan
            }

            contenidoCSV.agregarFila(values); // Agregar a la estructura
            model.addRow(values); // Agregar la fila al JTable
        }

    
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer el archivo CSV: " + e.getMessage());
    }
    
    
    //
         // Personalizar las barras de desplazamiento
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
        verticalScrollBar.setUI(new Principal2.CustomScrollBarUI());

        JScrollBar horizontalScrollBar = jScrollPane1.getHorizontalScrollBar();
        horizontalScrollBar.setUI(new Principal2.CustomScrollBarUI());
        
        
    
        
    }
  
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        table1 = new javax.swing.JScrollPane();
        JTableCSV = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSeleccionar1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        datoslbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSlider1 = new javax.swing.JSlider();

        jPanel6.setBackground(new java.awt.Color(0, 38, 79));
        jPanel6.setForeground(new java.awt.Color(0, 38, 79));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modelo para el Futuro de Oaxaca de Juárez");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(1101, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(823, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        Panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 20, 490));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 38, 79));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackButton.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Ingresar Datos(Exel)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addContainerGap(834, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(388, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(380, 380, 380)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(24, 24, 24)))
        );

        Panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 940, 80));

        btnSeleccionar.setBackground(new java.awt.Color(255, 153, 51));
        btnSeleccionar.setForeground(new java.awt.Color(153, 153, 153));
        btnSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel13.setText("Cargar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout btnSeleccionarLayout = new javax.swing.GroupLayout(btnSeleccionar);
        btnSeleccionar.setLayout(btnSeleccionarLayout);
        btnSeleccionarLayout.setHorizontalGroup(
            btnSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        btnSeleccionarLayout.setVerticalGroup(
            btnSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 170, 40));

        table1.setColumnHeaderView(null);
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JTableCSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tasa natalidad normal", "Esperanza de vida normal", "Relacion desechos-contaminacion", "Ocupacion inadecuada de residuos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setViewportView(JTableCSV);

        Panel1.add(table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 820, 300));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Panel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 820, 790, 420));

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setForeground(new java.awt.Color(0, 52, 107));

        jPanel16.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Panel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1340, 790, 420));

        jPanel17.setBackground(new java.awt.Color(153, 153, 153));
        jPanel17.setForeground(new java.awt.Color(0, 98, 107));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel14.setText("Impacto ambiental en la tasa de natalidad");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel14)
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Panel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1290, 790, 40));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel10.setText("(años)");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Tiempo de simulación:");
        Panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        btnSeleccionar1.setBackground(new java.awt.Color(255, 153, 51));
        btnSeleccionar1.setForeground(new java.awt.Color(153, 153, 153));
        btnSeleccionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionar1MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel17.setText("Graficar");

        javax.swing.GroupLayout btnSeleccionar1Layout = new javax.swing.GroupLayout(btnSeleccionar1);
        btnSeleccionar1.setLayout(btnSeleccionar1Layout);
        btnSeleccionar1Layout.setHorizontalGroup(
            btnSeleccionar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeleccionar1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btnSeleccionar1Layout.setVerticalGroup(
            btnSeleccionar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeleccionar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel1.add(btnSeleccionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 120, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        Panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 160, 30));

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setForeground(new java.awt.Color(0, 98, 107));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setText("Daño ambiental para esperanza de vida ");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel15)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Panel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, -1, -1));

        datoslbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Panel1.add(datoslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 250, 20));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ejemplo de CSV a ingresar:");
        Panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "año 1", "año 2", "año 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        Panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 60));

        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        Panel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 330, 40));

        jScrollPane1.setViewportView(Panel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       
        
         String mensaje = "<html><body><p style='width: 250px;'>⚠️ <b>¿Está seguro de que quiere salir?</b><br><br>"
                   + "Si sale ahora, <i>sus gráficos cuidadosamente generados</i> desaparecerán "
                   + "y no podrán recuperarse. ¡Piensa en todo el trabajo que pusiste en ellos!<br><br>"
                   + "¿Realmente quieres arriesgarte a perderlos?</p></body></html>";

    // Muestra el JOptionPane con opciones
    int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Confirmación de salida",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

    // Verifica la respuesta del usuario
    if (opcion == JOptionPane.OK_OPTION) {
        // Código para salir de la aplicación
        this.dispose();
        Principal2 ventana = new Principal2();
        ventana.setVisible(true);
    }
       
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17MouseClicked

    private void btnSeleccionar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionar1MouseClicked
         
        int cantidadDeFilas = Integer.parseInt(jTextField1.getText());  // 'añosSlider' es el slider con la cantidad de filas a generar

        // Llamar al método que genera los nuevos datos
        GenerarDatos.generarMasDatos(JTableCSV, cantidadDeFilas);      // TODO add your handling code here:
        calcularValores(); 
        
        GraficaSimulacion.graficarDesdeTabla(JTableCSV, jPanel8);  // TODO add your handling code here:
        GraficaSimulacionTn.graficarDesdeTabla(JTableCSV, jPanel16); 
    }//GEN-LAST:event_btnSeleccionar1MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
         
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        // Llama al método del botón al presionar Enter
                      
                    }
        char c = evt.getKeyChar();
                    // Permitir solo dígitos y teclas de control (como borrar)
                    if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
                        evt.consume(); // Ignorar el evento
                    }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void btnSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseClicked
        cargarCsv();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_CSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableCSV;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel btnSeleccionar;
    private javax.swing.JPanel btnSeleccionar1;
    private javax.swing.JLabel datoslbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane table1;
    // End of variables declaration//GEN-END:variables

    private void cargarCsv() {
     ContenidoCSV contenidoCSV = new ContenidoCSV();
        
        // Cargar los datos desde el archivo CSV
        contenidoCSV.cargarDesdeArchivo();

        // Obtener los datos del archivo CSV
        String[] encabezados = contenidoCSV.obtenerEncabezados();
        List<String[]> filas = contenidoCSV.obtenerFilas();

        // Crear el modelo de la tabla con los encabezados
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(encabezados);

        // Agregar las filas al modelo
        for (String[] fila : filas) {
            model.addRow(fila);
        }

        // Asignar el modelo de la tabla al JTable
        JTableCSV.setModel(model);
        originalModel=model;
}
  
    
    private void calcularValores() {
    DefaultTableModel model = (DefaultTableModel) JTableCSV.getModel();
    int rowCount = model.getRowCount();
    if (rowCount == 0) {
        datoslbl.setText("La tabla está vacía. Carga un archivo CSV primero.");
        return;
    }

    // Asegurarse de que las columnas adicionales para resultados existan
    if (model.getColumnCount() < 6) {
        model.addColumn("Daño Ambiental");
        model.addColumn("Tasa de Natalidad Calculada");
        model.addColumn("Esperanza de Vida Calculada");
    }

    try {
        for (int i = 0; i < rowCount; i++) {
            double tasaNatalidadNormal = Double.parseDouble((String) model.getValueAt(i, 0));
            double esperanzaVidaNormal = Double.parseDouble((String) model.getValueAt(i, 1));
            double relacionDesechos = Double.parseDouble((String) model.getValueAt(i, 2));
            double ocupacionInadecuada = Double.parseDouble((String) model.getValueAt(i, 3));

            // Cálculo de daño ambiental
            double danioAmbiental = relacionDesechos + ocupacionInadecuada;

            // Cálculo de tasa de natalidad
            double tasaNatalidad = tasaNatalidadNormal - (danioAmbiental * 8.35e-5);

            // Cálculo de esperanza de vida
            double esperanzaVida = esperanzaVidaNormal * (1 - danioAmbiental * 0.07);

            // Agregar los resultados calculados directamente en las nuevas columnas
            model.setValueAt(String.format("%.4f", danioAmbiental), i, 4); // Columna "Daño Ambiental"
            model.setValueAt(String.format("%.4f", tasaNatalidad), i, 5); // Columna "Tasa de Natalidad Calculada"
            model.setValueAt(String.format("%.2f", esperanzaVida), i, 6); // Columna "Esperanza de Vida Calculada"
        }
        datoslbl.setVisible(true);
        datoslbl.setText("Valores calculados y añadidos a la tabla.");
    } catch (Exception ex) {
        datoslbl.setVisible(true);
        datoslbl.setText("Error en el cálculo: " + ex.getMessage());
    }
}
    
    
    
    static class CustomScrollBarUI extends BasicScrollBarUI {
        private static final int THUMB_SIZE = 10;

        @Override
        protected void configureScrollBarColors() {
            this.thumbColor = new Color(153,153,153); // Color del "pulgar"
            this.trackColor = new Color(255,255,255); // Color de la pista
        }

        protected Dimension getThumbSize() {
            return new Dimension(THUMB_SIZE, THUMB_SIZE);
        }

        @Override
        protected JButton createDecreaseButton(int orientation) {
            return createZeroButton(); // Sin botones
        }

        @Override
        protected JButton createIncreaseButton(int orientation) {
            return createZeroButton(); // Sin botones
        }

        private JButton createZeroButton() {
            JButton button = new JButton();
            button.setPreferredSize(new Dimension(0, 0));
            button.setMinimumSize(new Dimension(0, 0));
            button.setMaximumSize(new Dimension(0, 0));
            return button;
        }
    }

}
